// Generated by generate-codex-mirror.mjs
// Reference: codex-client/src/sse.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "codex-client",
	referencePath: "codex-client/src/sse.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
