// Generated by generate-codex-mirror.mjs
// Reference: aws-auth/src/config.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "aws-auth",
	referencePath: "aws-auth/src/config.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
