// Generated by generate-codex-mirror.mjs
// Reference: analytics/src/facts.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "analytics",
	referencePath: "analytics/src/facts.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
