// Generated by generate-codex-mirror.mjs
// Reference: chatgpt/tests/suite/apply_command_e2e.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "chatgpt",
	referencePath: "chatgpt/tests/suite/apply_command_e2e.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
