// Generated by generate-codex-mirror.mjs
// Reference: execpolicy-legacy/src/execv_checker.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "execpolicy-legacy",
	referencePath: "execpolicy-legacy/src/execv_checker.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
