// Generated by generate-codex-mirror.mjs
// Reference: tools/src/responses_api.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "tools",
	referencePath: "tools/src/responses_api.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
