// Generated by generate-codex-mirror.mjs
// Reference: memories/read/src/metrics.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "memories",
	referencePath: "memories/read/src/metrics.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
