// Generated by generate-codex-mirror.mjs
// Reference: uds/src/lib_tests.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "uds",
	referencePath: "uds/src/lib_tests.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
