// Generated by generate-codex-mirror.mjs
// Reference: agent-graph-store/src/types.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "agent-graph-store",
	referencePath: "agent-graph-store/src/types.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
