// Generated by generate-codex-mirror.mjs
// Reference: state/src/extract.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "state",
	referencePath: "state/src/extract.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
