// Generated by generate-codex-mirror.mjs
// Reference: utils/sandbox-summary/src/sandbox_summary.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "utils",
	referencePath: "utils/sandbox-summary/src/sandbox_summary.rs",
	reason: "native sandbox",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
