// Generated by generate-codex-mirror.mjs
// Reference: core/src/context/plugin_instructions.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "core",
	referencePath: "core/src/context/plugin_instructions.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
