// Generated by generate-codex-mirror.mjs
// Reference: features/src/legacy.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "features",
	referencePath: "features/src/legacy.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
