// Generated by generate-codex-mirror.mjs
// Reference: connectors/src/merge.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "connectors",
	referencePath: "connectors/src/merge.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
