import { defineConfig } from "tsup";

export default defineConfig({
	bundle: true,
	clean: false,
	dts: false,
	entry: {
		index: "src/index.ts",
		"shadcn/index": "src/shadcn/index.ts",
	},
	external: [
		"@jrkropp/codex-js",
		"@jrkropp/codex-js/client",
		"@legendapp/list",
		"@legendapp/list/react",
		"@lexical/react",
		"@lexical/react/LexicalComposer",
		"@lexical/react/LexicalComposerContext",
		"@lexical/react/LexicalContentEditable",
		"@lexical/react/LexicalErrorBoundary",
		"@lexical/react/LexicalHistoryPlugin",
		"@lexical/react/LexicalOnChangePlugin",
		"@lexical/react/LexicalPlainTextPlugin",
		"class-variance-authority",
		"clsx",
		"cmdk",
		"lexical",
		"lucide-react",
		"radix-ui",
		"react",
		"react-dom",
		"react/jsx-runtime",
		"react-markdown",
		"remark-gfm",
		"tailwind-merge",
		"zustand",
		"zustand/middleware",
	],
	format: ["esm"],
	minify: false,
	outDir: "dist",
	platform: "browser",
	sourcemap: false,
	splitting: false,
	target: "es2022",
	treeshake: true,
});
