// Generated by generate-codex-mirror.mjs
// Reference: config/src/thread_config/proto/codex.thread_config.v1.rs

import { unsupportedCodexFeature } from "../../../../unsupported";

export const codexReference = {
	crate: "config",
	referencePath: "config/src/thread_config/proto/codex.thread_config.v1.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
