// Generated by generate-codex-mirror.mjs
// Reference: protocol/src/thread_id.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "protocol",
	referencePath: "protocol/src/thread_id.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
