// Generated by generate-codex-mirror.mjs
// Reference: exec/tests/suite/auth_env.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "exec",
	referencePath: "exec/tests/suite/auth_env.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
