// Generated by generate-codex-mirror.mjs
// Reference: exec/tests/suite/sandbox.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "exec",
	referencePath: "exec/tests/suite/sandbox.rs",
	reason: "native sandbox",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
