// Generated by generate-codex-mirror.mjs
// Reference: cli/src/app_cmd.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "cli",
	referencePath: "cli/src/app_cmd.rs",
	reason: "CLI only",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
