// Generated by generate-codex-mirror.mjs
// Reference: config/src/project_root_markers.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "config",
	referencePath: "config/src/project_root_markers.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
