// Generated by generate-codex-mirror.mjs
// Reference: plugin/src/plugin_id.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "plugin",
	referencePath: "plugin/src/plugin_id.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
