// Generated by generate-codex-mirror.mjs
// Reference: rollout-trace/src/reducer/code_cell.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "rollout-trace",
	referencePath: "rollout-trace/src/reducer/code_cell.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
