// Generated by generate-codex-mirror.mjs
// Reference: lmstudio/src/client.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "lmstudio",
	referencePath: "lmstudio/src/client.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
