// Generated by generate-codex-mirror.mjs
// Reference: core-plugins/src/remote/share.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "core-plugins",
	referencePath: "core-plugins/src/remote/share.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
