// Generated by generate-codex-mirror.mjs
// Reference: utils/json-to-toml/src/lib.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "utils",
	referencePath: "utils/json-to-toml/src/lib.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
