// Generated by generate-codex-mirror.mjs
// Reference: app-server/src/main.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "app-server",
	referencePath: "app-server/src/main.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
