// Generated by generate-codex-mirror.mjs
// Reference: exec-server/tests/file_system.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "exec-server",
	referencePath: "exec-server/tests/file_system.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
