// Generated by generate-codex-mirror.mjs
// Reference: models-manager/src/manager_tests.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "models-manager",
	referencePath: "models-manager/src/manager_tests.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
