// Generated by generate-codex-mirror.mjs
// Reference: apply-patch/tests/suite/scenarios.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "apply-patch",
	referencePath: "apply-patch/tests/suite/scenarios.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
