// Generated by generate-codex-mirror.mjs
// Reference: windows-sandbox-rs/src/conpty/mod.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "windows-sandbox-rs",
	referencePath: "windows-sandbox-rs/src/conpty/mod.rs",
	reason: "native sandbox",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
