// Generated by generate-codex-mirror.mjs
// Reference: app-server-transport/src/transport/websocket.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "app-server-transport",
	referencePath: "app-server-transport/src/transport/websocket.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
