import { defineConfig } from "tsup";

export default defineConfig({
	bundle: true,
	clean: true,
	dts: true,
	entry: {
		index: "src/index.ts",
		"client/index": "src/client/index.ts",
		"react/index": "src/react/index.ts",
		"server/index": "src/server/index.ts",
		"shadcn/index": "src/shadcn/index.ts",
		"testing/index": "src/testing/index.ts",
	},
	external: [
		"@legendapp/list",
		"@legendapp/list/react",
		"@lexical/react",
		"@lexical/react/LexicalComposer",
		"@lexical/react/LexicalComposerContext",
		"@lexical/react/LexicalContentEditable",
		"@lexical/react/LexicalErrorBoundary",
		"@lexical/react/LexicalHistoryPlugin",
		"@lexical/react/LexicalOnChangePlugin",
		"@lexical/react/LexicalPlainTextPlugin",
		"class-variance-authority",
		"clsx",
		"cmdk",
		"lexical",
		"lucide-react",
		"radix-ui",
		"react",
		"react-dom",
		"react/jsx-runtime",
		"react-markdown",
		"remark-gfm",
		"smol-toml",
		"tailwind-merge",
		"zustand",
		"zustand/middleware",
	],
	format: ["esm"],
	minify: false,
	outDir: "dist",
	platform: "browser",
	sourcemap: true,
	splitting: true,
	target: "es2022",
	treeshake: true,
});
