// Generated by generate-codex-mirror.mjs
// Reference: core-skills/src/env_var_dependencies.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "core-skills",
	referencePath: "core-skills/src/env_var_dependencies.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
