// Generated by generate-codex-mirror.mjs
// Reference: codex-mcp/src/connection_manager_tests.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "codex-mcp",
	referencePath: "codex-mcp/src/connection_manager_tests.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
