// Generated by generate-codex-mirror.mjs
// Reference: thread-manager-sample/src/main.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "thread-manager-sample",
	referencePath: "thread-manager-sample/src/main.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
