// Generated by generate-codex-mirror.mjs
// Reference: execpolicy/src/amend.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "execpolicy",
	referencePath: "execpolicy/src/amend.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
