// Generated by generate-codex-mirror.mjs
// Reference: tui/src/app/test_support.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "tui",
	referencePath: "tui/src/app/test_support.rs",
	reason: "TUI only",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
