// Generated by generate-codex-mirror.mjs
// Reference: codex-api/src/api_bridge_tests.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "codex-api",
	referencePath: "codex-api/src/api_bridge_tests.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
