// Generated by generate-codex-mirror.mjs
// Reference: utils/path-utils/src/env.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "utils",
	referencePath: "utils/path-utils/src/env.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
