// Generated by generate-codex-mirror.mjs
// Reference: thread-store/src/local/test_support.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "thread-store",
	referencePath: "thread-store/src/local/test_support.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
