// Generated by generate-codex-mirror.mjs
// Reference: responses-api-proxy/src/dump.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "responses-api-proxy",
	referencePath: "responses-api-proxy/src/dump.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
