// Generated by generate-codex-mirror.mjs
// Reference: apply-patch/src/standalone_executable.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "apply-patch",
	referencePath: "apply-patch/src/standalone_executable.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
