// Generated by generate-codex-mirror.mjs
// Reference: device-key/src/platform.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "device-key",
	referencePath: "device-key/src/platform.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
