// Generated by generate-codex-mirror.mjs
// Reference: debug-client/src/reader.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "debug-client",
	referencePath: "debug-client/src/reader.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
