// Generated by generate-codex-mirror.mjs
// Reference: chatgpt/src/connectors.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "chatgpt",
	referencePath: "chatgpt/src/connectors.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
