// Generated by generate-codex-mirror.mjs
// Reference: test-binary-support/lib.rs

import { unsupportedCodexFeature } from "../unsupported";

export const codexReference = {
	crate: "test-binary-support",
	referencePath: "test-binary-support/lib.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
