// Generated by generate-codex-mirror.mjs
// Reference: shell-escalation/src/unix/execve_wrapper.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "shell-escalation",
	referencePath: "shell-escalation/src/unix/execve_wrapper.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
