// Generated by generate-codex-mirror.mjs
// Reference: hooks/src/output_spill_tests.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "hooks",
	referencePath: "hooks/src/output_spill_tests.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
