// Generated by generate-codex-mirror.mjs
// Reference: core/tests/common/streaming_sse.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "core",
	referencePath: "core/tests/common/streaming_sse.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
