// Generated by generate-codex-mirror.mjs
// Reference: app-server/tests/suite/v2/turn_interrupt.rs

import { unsupportedCodexFeature } from "../../../../unsupported";

export const codexReference = {
	crate: "app-server",
	referencePath: "app-server/tests/suite/v2/turn_interrupt.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
