// Generated by generate-codex-mirror.mjs
// Reference: network-proxy/src/certs.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "network-proxy",
	referencePath: "network-proxy/src/certs.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
