// Generated by generate-codex-mirror.mjs
// Reference: sandboxing/src/lib.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "sandboxing",
	referencePath: "sandboxing/src/lib.rs",
	reason: "native sandbox",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
