// Generated by generate-codex-mirror.mjs
// Reference: mcp-server/src/exec_approval.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "mcp-server",
	referencePath: "mcp-server/src/exec_approval.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
