// Generated by generate-codex-mirror.mjs
// Reference: utils/pty/src/win/mod.rs

import { unsupportedCodexFeature } from "../../../../unsupported";

export const codexReference = {
	crate: "utils",
	referencePath: "utils/pty/src/win/mod.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
