// Generated by generate-codex-mirror.mjs
// Reference: core/src/tools/handlers/agent_jobs.rs

import { unsupportedCodexFeature } from "../../../../unsupported";

export const codexReference = {
	crate: "core",
	referencePath: "core/src/tools/handlers/agent_jobs.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
