// Generated by generate-codex-mirror.mjs
// Reference: rollout/src/state_db_tests.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "rollout",
	referencePath: "rollout/src/state_db_tests.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
