// Generated by generate-codex-mirror.mjs
// Reference: codex-backend-openapi-models/src/models/rate_limit_window_snapshot.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "codex-backend-openapi-models",
	referencePath: "codex-backend-openapi-models/src/models/rate_limit_window_snapshot.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
