// Generated by generate-codex-mirror.mjs
// Reference: shell-command/src/command_safety/windows_dangerous_commands.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "shell-command",
	referencePath: "shell-command/src/command_safety/windows_dangerous_commands.rs",
	reason: "native sandbox",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
