// Generated by generate-codex-mirror.mjs
// Reference: stdio-to-uds/src/main.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "stdio-to-uds",
	referencePath: "stdio-to-uds/src/main.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
