// Generated by generate-codex-mirror.mjs
// Reference: core/src/tools/sandboxing_tests.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "core",
	referencePath: "core/src/tools/sandboxing_tests.rs",
	reason: "native sandbox",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
