// Generated by generate-codex-mirror.mjs
// Reference: memories/mcp/src/backend.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "memories",
	referencePath: "memories/mcp/src/backend.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
