// Generated by generate-codex-mirror.mjs
// Reference: external-agent-sessions/src/records.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "external-agent-sessions",
	referencePath: "external-agent-sessions/src/records.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
