// Generated by generate-codex-mirror.mjs
// Reference: backend-client/src/client.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "backend-client",
	referencePath: "backend-client/src/client.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
