// Generated by generate-codex-mirror.mjs
// Reference: otel/src/metrics/tags.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "otel",
	referencePath: "otel/src/metrics/tags.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
