// Generated by generate-codex-mirror.mjs
// Reference: memories/write/src/extensions/mod.rs

import { unsupportedCodexFeature } from "../../../../unsupported";

export const codexReference = {
	crate: "memories",
	referencePath: "memories/write/src/extensions/mod.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
