// Generated by generate-codex-mirror.mjs
// Reference: ollama/src/url.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "ollama",
	referencePath: "ollama/src/url.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
