// Generated by generate-codex-mirror.mjs
// Reference: realtime-webrtc/src/native.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "realtime-webrtc",
	referencePath: "realtime-webrtc/src/native.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
