// Generated by generate-codex-mirror.mjs
// Reference: cloud-tasks/tests/env_filter.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "cloud-tasks",
	referencePath: "cloud-tasks/tests/env_filter.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
