// Generated by generate-codex-mirror.mjs
// Reference: hooks/src/events/pre_tool_use.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "hooks",
	referencePath: "hooks/src/events/pre_tool_use.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
