// Generated by generate-codex-mirror.mjs
// Reference: model-provider/src/amazon_bedrock/mod.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "model-provider",
	referencePath: "model-provider/src/amazon_bedrock/mod.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
