// Generated by generate-codex-mirror.mjs
// Reference: code-mode/src/runtime/callbacks.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "code-mode",
	referencePath: "code-mode/src/runtime/callbacks.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
