// Generated by generate-codex-mirror.mjs
// Reference: exec/src/cli_tests.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "exec",
	referencePath: "exec/src/cli_tests.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
