// Generated by generate-codex-mirror.mjs
// Reference: linux-sandbox/src/lib.rs

import { unsupportedCodexFeature } from "../../unsupported";

export const codexReference = {
	crate: "linux-sandbox",
	referencePath: "linux-sandbox/src/lib.rs",
	reason: "native sandbox",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
