// Generated by generate-codex-mirror.mjs
// Reference: core/src/tools/handlers/shell/container_exec.rs

import { unsupportedCodexFeature } from "../../../../../unsupported";

export const codexReference = {
	crate: "core",
	referencePath: "core/src/tools/handlers/shell/container_exec.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
