// Generated by generate-codex-mirror.mjs
// Reference: app-server/src/request_processors/thread_summary_tests.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "app-server",
	referencePath: "app-server/src/request_processors/thread_summary_tests.rs",
	reason: "native process",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
