// Generated by generate-codex-mirror.mjs
// Reference: app-server/src/request_processors/windows_sandbox_processor.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "app-server",
	referencePath: "app-server/src/request_processors/windows_sandbox_processor.rs",
	reason: "native sandbox",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
