// Generated by generate-codex-mirror.mjs
// Reference: utils/cli/src/format_env_display.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "utils",
	referencePath: "utils/cli/src/format_env_display.rs",
	reason: "CLI only",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
