// Generated by generate-codex-mirror.mjs
// Reference: skills/build.rs

import { unsupportedCodexFeature } from "../unsupported";

export const codexReference = {
	crate: "skills",
	referencePath: "skills/build.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
