// Generated by generate-codex-mirror.mjs
// Reference: login/tests/suite/device_code_login.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "login",
	referencePath: "login/tests/suite/device_code_login.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
