// Generated by generate-codex-mirror.mjs
// Reference: login/tests/suite/login_server_e2e.rs

import { unsupportedCodexFeature } from "../../../unsupported";

export const codexReference = {
	crate: "login",
	referencePath: "login/tests/suite/login_server_e2e.rs",
	reason: "not ported yet",
	status: "stubbed",
} as const;

export function unsupported(..._args: unknown[]): never {
	return unsupportedCodexFeature(codexReference);
}

export default unsupported;
